sudo: false

language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"

cache:
  directories:
    - node_modules/

before_script:
  - node --version
  - npm --version
  - npm install -g gulp

script:
  - npm test

after_script:
  - npm run coveralls

matrix:
  fast_finish: true
